DROP SCHEMA projet Cascade;
CREATE SCHEMA projet;

CREATE  TABLE projet.departements (
code_departement CHAR(3) NOT NULL,
nom VARCHAR  (255) NOT NULL,
num_version INTEGER NOT NULL,
CONSTRAINT code_departement PRIMARY KEY (code_departement)
);

CREATE  TABLE projet.pays (
code_pays char(2) NOT NULL,
programme VARCHAR  (255) NOT NULL,
nom VARCHAR  (255) NOT NULL,
CONSTRAINT code_pays_pk PRIMARY KEY (code_pays)
);

CREATE  TABLE projet.annulations (
num_annulation serial NOT NULL,
descriptif_raison VARCHAR  (255) NOT NULL,
generique boolean NOT NULL,
num_version INTEGER NOT NULL,
CONSTRAINT num_annulation_pk PRIMARY KEY (num_annulation)
);
CREATE  TABLE projet.utilisateurs (
num_utilisateur serial NOT NULL,
mdp  VARCHAR (255) NOT NULL,
pseudo  VARCHAR  (255)  NOT NULL,
nom VARCHAR  (255) NOT NULL,
prenom VARCHAR (255) NOT NULL,
departement CHAR (3) NOT NULL,
date_naissance DATE  NULL,
adresse varchar(255) NULL,
telephone varchar(255) NULL,
email varchar(255) NULL,
nationalite varchar(255) NULL,
titre varchar(255) NULL,
sexe char(1) NULL,
nbr_annee_ens_sup INTEGER NULL,
titulaire_compte varchar(255) NULL,
num_compte varchar(255) NULL,
nom_banque varchar(255) NULL,
code_bic varchar(255) NULL,
date_inscription TIMESTAMP NULL,
type_user varchar(255)  NOT NULL,
num_version INTEGER NOT NULL,
CONSTRAINT num_utilisateur_pk PRIMARY KEY (num_utilisateur),
CONSTRAINT departement_fkey FOREIGN KEY (departement) REFERENCES projet.departements (code_departement)
);

CREATE  TABLE projet.partenaires (
num_partenaire serial NOT NULL,
nom_affaire VARCHAR  (255) NOT NULL,
nom_legal VARCHAR  (255) NOT NULL,
nom_complet VARCHAR  (255) NOT NULL,
nombre_employes INTEGER NOT NULL,
adresse varchar(255) NOT NULL,
createur INTEGER NOT NULL,
code_pays char(2) NOT NULL,
region varchar(255) NOT NULL,
code_postal varchar(255) NOT NULL,
ville varchar(255) NOT NULL,
email varchar(255) NOT NULL,
site_web varchar(255) NOT NULL,
telephone varchar(255) NOT NULL,
stage varchar(255) NOT NULL,
agree BOOLEAN  NOT NULL,
type_entreprise varchar(255) NOT NULL,
num_version INTEGER NOT NULL,
supprime BOOLEAN NOT NULL,
CONSTRAINT num_partenaire_pk PRIMARY KEY (num_partenaire),
CONSTRAINT createur_fkey FOREIGN KEY (createur) REFERENCES projet.utilisateurs (num_utilisateur),
CONSTRAINT pays_fkey FOREIGN KEY (code_pays) REFERENCES projet.pays (code_pays)
);

CREATE TABLE projet.partenairesParDepartement(
partenaire INTEGER NOT NULL,
code_departement CHAR(3) NOT NULL,
num_version INTEGER NOT NULL,
CONSTRAINT code_departementEtpartenaire_pk PRIMARY KEY (code_departement,partenaire),
CONSTRAINT partenaire_fkey FOREIGN KEY (partenaire) REFERENCES projet.partenaires (num_partenaire),
CONSTRAINT departement_fkey FOREIGN KEY (code_departement) REFERENCES  projet.departements  (code_departement)
);

CREATE  TABLE projet.demandes(
num_demande serial NOT NULL,
preference INTEGER  NOT NULL,
ville varchar(255) NULL,
stage varchar(255) NOT NULL,
num_quadri INTEGER  NULL,
num_annulation INTEGER NULL,
num_partenaire INTEGER NULL,
num_etudiant INTEGER NOT NULL,
code_pays char(2) NULL,
validee BOOLEAN NOT NULL,	
programme varchar(255) NULL,
date_introduction TIMESTAMP NOT NULL,
num_version INTEGER NOT NULL,
annee_academique varchar NOT NULL,
CONSTRAINT num_demande_pk PRIMARY KEY (num_demande),
CONSTRAINT pays_fkey FOREIGN KEY (code_pays) REFERENCES projet.pays (code_pays),
CONSTRAINT annulation_fkey FOREIGN KEY (num_annulation) REFERENCES projet.annulations(num_annulation),
CONSTRAINT num_partenaire_fkey FOREIGN KEY (num_partenaire) REFERENCES projet.partenaires(num_partenaire),
CONSTRAINT etudiant_fkey FOREIGN KEY (num_etudiant) REFERENCES projet.utilisateurs (num_utilisateur)
);

CREATE TABLE projet.mobilites(
num_mobilite serial NOT NULL,
num_etudiant INTEGER NOT NULL,
num_demande INTEGER NOT NULL,
code_pays char(2) NOT NULL,
ville varchar NOT NULL,
num_partenaire INTEGER NOT NULL,
etat varchar(255) NOT NULL,
num_annulation INTEGER NULL,
annee_academique varchar(15) NOT NULL,
proEco BOOLEAN NOT NULL,
mobility_Tool BOOLEAN NOT NULL,
mobi BOOLEAN NOT NULL,
stage varchar(255) NOT NULL,
num_quadri INTEGER  NOT NULL,
num_version INTEGER NOT NULL,
CONSTRAINT num_mobilite_pk PRIMARY KEY (num_mobilite),
CONSTRAINT pays_fkey FOREIGN KEY (code_pays) REFERENCES projet.pays (code_pays),
CONSTRAINT annulation_fkey FOREIGN KEY (num_annulation) REFERENCES projet.annulations(num_annulation),
CONSTRAINT etudiant_fkey FOREIGN KEY (num_etudiant) REFERENCES projet.utilisateurs (num_utilisateur),
CONSTRAINT num_partenaire_fkey FOREIGN KEY (num_partenaire) REFERENCES projet.partenaires(num_partenaire),
CONSTRAINT num_demande_fkey FOREIGN KEY (num_demande) REFERENCES projet.demandes(num_demande)
);

CREATE  TABLE projet.docs_retours (
num_retour serial NOT NULL,
attestation_sejour BOOLEAN NOT NULL,
releve_note_ou_certif_stage BOOLEAN NOT NULL,
preuve_passage_test BOOLEAN NOT NULL,
rapport_final BOOLEAN NOT NULL,
date_retour TIMESTAMP,
num_etudiant INTEGER NOT NULL,
num_mobilite INTEGER NOT NULL,
num_version INTEGER NOT NULL,
CONSTRAINT num_retourPk PRIMARY KEY(num_retour),
CONSTRAINT etudiant_fkey FOREIGN KEY (num_etudiant) REFERENCES projet.utilisateurs (num_utilisateur),
CONSTRAINT num_mobilite_fkey FOREIGN KEY (num_mobilite) REFERENCES projet.mobilites(num_mobilite)

);

CREATE  TABLE projet.docs_departs (
num_depart serial NOT NULL,
contrat_bourse BOOLEAN NOT NULL,
charte_etudiant BOOLEAN NOT NULL,
convention_stage_ou_etude BOOLEAN NOT NULL,
preuve_test_langue BOOLEAN NOT NULL,
doc_engagement BOOLEAN NOT NULL,
date_depart TIMESTAMP,
num_etudiant INTEGER NOT NULL,
num_mobilite INTEGER NOT NULL,
num_version INTEGER NOT NULL,
CONSTRAINT num_deparPk PRIMARY KEY(num_depart),
CONSTRAINT etudiant_fkey FOREIGN KEY (num_etudiant) REFERENCES projet.utilisateurs (num_utilisateur),
CONSTRAINT num_mobilite_fkey FOREIGN KEY (num_mobilite) REFERENCES projet.mobilites(num_mobilite)
);

CREATE  TABLE projet.demande_paiements (
num_paiement serial NOT NULL,
date_execution TIMESTAMP NOT NULL,
num_etudiant INTEGER NOT NULL,
num_professeur INTEGER NOT NULL,
num_mobilite INTEGER NOT NULL,
num_version INTEGER NOT NULL,
CONSTRAINT num_paiement_PK PRIMARY KEY(num_paiement),
CONSTRAINT etudiant_fkey FOREIGN KEY (num_etudiant) REFERENCES projet.utilisateurs (num_utilisateur),
CONSTRAINT professeur_fkey FOREIGN KEY (num_professeur) REFERENCES projet.utilisateurs (num_utilisateur),
CONSTRAINT num_mobilite_fkey FOREIGN KEY (num_mobilite) REFERENCES projet.mobilites(num_mobilite)
);
INSERT INTO projet.departements (code_departement, nom, num_version) VALUES
('BIN', 'Informatique',1),
('BBM', 'Bio-Medical',1),
('BDI', 'Dietetique',1),
('BIM', 'Imagerie Medicale',1),
('BCH', 'Bio-Chimie',1);
INSERT INTO projet.pays (code_pays,nom,programme ) VALUES
('AF', 'Afghanistan', 'Fame'),
('AL', 'Albanie', 'Fame'),
('AQ', 'Antarctique', 'Fame'),
('DZ', 'Algérie', 'Fame'),
('AS', 'Samoa Américaines', 'Fame'),
('AD', 'Andorre', 'Fame'),
('AO', 'Angola', 'Fame'),
('AG', 'Antigua-et-Barbuda', 'Fame'),
('AZ', 'Azerbaïdjan', 'Fame'),
('AR', 'Argentine', 'Fame'),
('AU', 'Australie', 'Fame'),
('AT', 'Autriche', 'Erasmus'),
('BS', 'Bahamas', 'Fame'),
('BH', 'Bahreïn', 'Fame'),
('BD', 'Bangladesh', 'Fame'),
('AM', 'Arménie', 'Fame'),
('BB', 'Barbade', 'Fame'),
('BE', 'Belgique', 'Erabel'),
('BM', 'Bermudes', 'Fame'),
('BT', 'Bhoutan', 'Fame'),
('BO', 'Bolivie', 'Fame'),
('BA', 'Bosnie-Herzégovine', 'Fame'),
('BW', 'Botswana', 'Fame'),
('BV', 'Île Bouvet', 'Fame'),
('BR', 'Brésil', 'Fame'),
('BZ', 'Belize', 'Fame'),
('SB', 'Îles Salomon', 'Fame'),
('VG', 'Îles Vierges Britanniques', 'Fame'),
('BN', 'Brunéi Darussalam', 'Fame'),
('BG', 'Bulgarie', 'Erasmus'),
('MM', 'Myanmar', 'Fame'),
('BI', 'Burundi', 'Fame'),
('BY', 'Bélarus', 'Fame'),
('KH', 'Cambodge', 'Fame'),
('CM', 'Cameroun', 'Fame'),
('CA', 'Canada', 'Fame'),
('CV', 'Cap-vert', 'Fame'),
('KY', 'Îles Caïmanes', 'Fame'),
('CF', 'République Centrafricaine', 'Fame'),
('LK', 'Sri Lanka', 'Fame'),
('TD', 'Tchad', 'Fame'),
('CL', 'Chili', 'Fame'),
('CN', 'Chine', 'Fame'),
('TW', 'Taïwan', 'Fame'),
('CX', 'Île Christmas', 'Fame'),
('CC', 'Îles Cocos (Keeling)', 'Fame'),
('CO', 'Colombie', 'Fame'),
('KM', 'Comores', 'Fame'),
('YT', 'Mayotte', 'Fame'),
('CG', 'République du Congo', 'Fame'),
('CD', 'République Démocratique du Congo', 'Fame'),
('CK', 'Îles Cook', 'Fame'),
('CR', 'Costa Rica', 'Fame'),
('HR', 'Croatie', 'Erasmus'),
('CU', 'Cuba', 'Fame'),
('CY', 'Chypre', 'Erasmus'),
('CZ', 'République Tchèque', 'Erasmus'),
('BJ', 'Bénin', 'Fame'),
('DK', 'Danemark', 'Erasmus'),
('DM', 'Dominique', 'Fame'),
('DO', 'République Dominicaine', 'Fame'),
('EC', 'Équateur', 'Fame'),
('SV', 'El Salvador', 'Fame'),
('GQ', 'Guinée Équatoriale', 'Fame'),
('ET', 'Éthiopie', 'Fame'),
('ER', 'Érythrée', 'Fame'),
('EE', 'Estonie', 'Erasmus'),
('FO', 'Îles Féroé', 'Fame'),
('FK', 'Îles (malvinas) Falkland', 'Fame'),
('GS', 'Géorgie du Sud et les Îles Sandwich du Sud', 'Fame'),
('FJ', 'Fidji', 'Fame'),
('FI', 'Finlande', 'Erasmus'),
('AX', 'Îles Åland', 'Fame'),
('FR', 'France', 'Erasmus'),
('GF', 'Guyane Française', 'Fame'),
('PF', 'Polynésie Française', 'Fame'),
('TF', 'Terres Australes Françaises', 'Fame'),
('DJ', 'Djibouti', 'Fame'),
('GA', 'Gabon', 'Fame'),
('GE', 'Géorgie', 'Fame'),
('GM', 'Gambie', 'Fame'),
('PS', 'Territoire Palestinien Occupé', 'Fame'),
('DE', 'Allemagne', 'Erasmus'),
('GH', 'Ghana', 'Fame'),
('GI', 'Gibraltar', 'Fame'),
('KI', 'Kiribati', 'Fame'),
('GR', 'Grèce', 'Erasmus'),
('GL', 'Groenland', 'Fame'),
('GD', 'Grenade', 'Fame'),
('GP', 'Guadeloupe', 'Fame'),
('GU', 'Guam', 'Fame'),
('GT', 'Guatemala', 'Fame'),
('GN', 'Guinée', 'Fame'),
('GY', 'Guyana', 'Fame'),
('HT', 'Haïti', 'Fame'),
('HM', 'Îles Heard et Mcdonald', 'Fame'),
('VA', 'Saint-Siège (état de la Cité du Vatican)', 'Fame'),
('HN', 'Honduras', 'Fame'),
('HK', 'Hong-Kong', 'Fame'),
('HU', 'Hongrie', 'Erasmus'),
('IS', 'Islande', 'Erasmus'),
('IN', 'Inde', 'Fame'),
('ID', 'Indonésie', 'Fame'),
('IR', 'Iran', 'Fame'),
('IQ', 'Iraq', 'Fame'),
('IE', 'Irlande', 'Erasmus'),
('IL', 'Israël', 'Fame'),
('IT', 'Italie', 'Erasmus'),
('CI', 'Côte d Ivoire', 'Fame'),
('JM', 'Jamaïque', 'Fame'),
('JP', 'Japon', 'Fame'),
('KZ', 'Kazakhstan', 'Fame'),
('JO', 'Jordanie', 'Fame'),
('KE', 'Kenya', 'Fame'),
('KP', 'République Populaire Démocratique de Corée', 'Fame'),
('KR', 'République de Corée', 'Fame'),
('KW', 'Koweït', 'Fame'),
('KG', 'Kirghizistan', 'Fame'),
('LA', 'République Démocratique Populaire Lao', 'Fame'),
('LB', 'Liban', 'Fame'),
('LS', 'Lesotho', 'Fame'),
('IO', 'Territoire Britannique de l Océan Indien', 'Fame'),
('LV', 'Lettonie', 'Erasmus'),
('LR', 'Libéria', 'Fame'),
('LY', 'Jamahiriya Arabe Libyenne', 'Fame'),
('LI', 'Liechtenstein', 'Erasmus'),
('LT', 'Lituanie', 'Erasmus'),
('LU', 'Luxembourg', 'Erasmus'),
('MO', 'Macao', 'Fame'),
('MG', 'Madagascar', 'Fame'),
('MW', 'Malawi', 'Fame'),
('MY', 'Malaisie', 'Fame'),
('MV', 'Maldives', 'Fame'),
('ML', 'Mali', 'Fame'),
('MT', 'Malte', 'Erasmus'),
('MQ', 'Martinique', 'Fame'),
('MR', 'Mauritanie', 'Fame'),
('MU', 'Maurice', 'Fame'),
('MX', 'Mexique', 'Fame'),
('MC', 'Monaco', 'Fame'),
('MN', 'Mongolie', 'Fame'),
('MD', 'République de Moldova', 'Fame'),
('MS', 'Montserrat', 'Fame'),
('MA', 'Maroc', 'Fame'),
('MZ', 'Mozambique', 'Fame'),
('OM', 'Oman', 'Fame'),
('NA', 'Namibie', 'Fame'),
('NR', 'Nauru', 'Fame'),
('NP', 'Népal', 'Fame'),
('NL', 'Pays-Bas', 'Erasmus'),
('AN', 'Antilles Néerlandaises', 'Fame'),
('AW', 'Aruba', 'Fame'),
('NC', 'Nouvelle-Calédonie', 'Fame'),
('VU', 'Vanuatu', 'Fame'),
('NZ', 'Nouvelle-Zélande', 'Fame'),
('NI', 'Nicaragua', 'Fame'),
('NE', 'Niger', 'Fame'),
('NG', 'Nigéria', 'Fame'),
('NU', 'Niué', 'Fame'),
('NF', 'Île Norfolk', 'Fame'),
('NO', 'Norvège', 'Erasmus'),
('MP', 'Îles Mariannes du Nord', 'Fame'),
('UM', 'Îles Mineures Éloignées des États-Unis', 'Fame'),
('FM', 'États Fédérés de Micronésie', 'Fame'),
('MH', 'Îles Marshall', 'Fame'),
('PW', 'Palaos', 'Fame'),
('PK', 'Pakistan', 'Fame'),
('PA', 'Panama', 'Fame'),
('PG', 'Papouasie-Nouvelle-Guinée', 'Fame'),
('PY', 'Paraguay', 'Fame'),
('PE', 'Pérou', 'Fame'),
('PH', 'Philippines', 'Fame'),
('PN', 'Pitcairn', 'Fame'),
('PL', 'Pologne', 'Erasmus'),
('PT', 'Portugal', 'Erasmus'),
('GW', 'Guinée-Bissau', 'Fame'),
('TL', 'Timor-Leste', 'Fame'),
('PR', 'Porto Rico', 'Fame'),
('QA', 'Qatar', 'Fame'),
('RE', 'Réunion', 'Fame'),
('RO', 'Roumanie', 'Erasmus'),
('RU', 'Fédération de Russie', 'Fame'),
('RW', 'Rwanda', 'Fame'),
('SH', 'Sainte-Hélène', 'Fame'),
('KN', 'Saint-Kitts-et-Nevis', 'Fame'),
('AI', 'Anguilla', 'Fame'),
('LC', 'Sainte-Lucie', 'Fame'),
('PM', 'Saint-Pierre-et-Miquelon', 'Fame'),
('VC', 'Saint-Vincent-et-les Grenadines', 'Fame'),
('SM', 'Saint-Marin', 'Fame'),
('ST', 'Sao Tomé-et-Principe', 'Fame'),
('SA', 'Arabie Saoudite', 'Fame'),
('SN', 'Sénégal', 'Fame'),
('SC', 'Seychelles', 'Fame'),
('SL', 'Sierra Leone', 'Fame'),
('SG', 'Singapour', 'Fame'),
('SK', 'Slovaquie', 'Erasmus'),
('VN', 'Viet Nam', 'Fame'),
('SI', 'Slovénie', 'Erasmus'),
('SO', 'Somalie', 'Fame'),
('ZA', 'Afrique du Sud', 'Fame'),
('ZW', 'Zimbabwe', 'Fame'),
('ES', 'Espagne', 'Fame'),
('EH', 'Sahara Occidental', 'Fame'),
('SD', 'Soudan', 'Fame'),
('SR', 'Suriname', 'Fame'),
('SJ', 'Svalbard etÎle Jan Mayen', 'Fame'),
('SZ', 'Swaziland', 'Fame'),
('SE', 'Suède', 'Erasmus'),
('CH', 'Suisse', 'Erasmus'),
('SY', 'République Arabe Syrienne', 'Fame'),
('TJ', 'Tadjikistan', 'Fame'),
('TH', 'Thaïlande', 'Fame'),
('TG', 'Togo', 'Fame'),
('TK', 'Tokelau', 'Fame'),
('TO', 'Tonga', 'Fame'),
('TT', 'Trinité-et-Tobago', 'Fame'),
('AE', 'Émirats Arabes Unis', 'Fame'),
('TN', 'Tunisie', 'Fame'),
('TR', 'Turquie', 'Erasmus'),
('TM', 'Turkménistan', 'Fame'),
('TC', 'Îles Turks et Caïques', 'Fame'),
('TV', 'Tuvalu', 'Fame'),
('UG', 'Ouganda', 'Fame'),
('UA', 'Ukraine', 'Fame'),
('MK', 'Ex-République Yougoslave de Macédoine', 'Erasmus'),
('EG', 'Égypte', 'Fame'),
('GB', 'Royaume-Uni', 'Erasmus'),
('IM', 'Île de Man', 'Fame'),
('TZ', 'République-Unie de Tanzanie', 'Fame'),
('US', 'États-Unis', 'Fame'),
('VI', 'Îles Vierges des États-Unis', 'Fame'),
('BF', 'Burkina Faso', 'Fame'),
('UY', 'Uruguay', 'Fame'),
('UZ', 'Ouzbékistan', 'Fame'),
('VE', 'Venezuela', 'Fame'),
('WF', 'Wallis et Futuna', 'Fame'),
('WS', 'Samoa', 'Fame'),
('YE', 'Yémen', 'Fame'),
('CS', 'Serbie-et-Monténégro', 'Fame'),
('ZM', 'Zambie', 'Fame');
